### ISSUE TITLE
Comment with NatSpec Format

### ISSUE THREAD

**Issue by rya-sge** [CMTA/DVP#10]
If a new version is released, it will be good/more clear to comment the functions with the [NatSpec Format](https://docs.soliditylang.org/en/develop/natspec-format.html).

> /// @notice Calculate tree age in years, rounded up, for live trees
>  /// @dev The Alexandr N. Tetearing algorithm could increase precision
>  /// @param rings The number of rings from dendrochronological sample
>  /// @return Age in years, rounded up for partial years

**Comment by mh-targens** [comment]
https://github.com/CMTA/DVP/pull/23
(see docs/NatSpec/README.md)
