### ISSUE TITLE
OpenZeppelin update

### ISSUE THREAD

**Issue by rya-sge** [CMTA/DVP#11]
It would be good to upgrade the OpenZeppelin version to the new release version: [4.8.0](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable) if it is possible.

Warning:  the CMTAT version 2 uses the version 4.7.3 at the moment

**Comment by mh-targens** [comment]
https://github.com/CMTA/DVP/pull/22 (Import open zeppelin 4.8.0)
