### ISSUE TITLE
Integration test with CMTAT

### ISSUE THREAD

**Issue by rya-sge** [CMTA/DVP#14]
It would be good to have integration test with the CMTAT.
Perhaps, it is already the case but I do not see any tests which use the CMTAT

**Comment by mh-targens** [comment]
The DvP contract interacts with the IERC20Upgradeable interface, which is implemented by CMTAT (-> EnforcementModule -> ERC20Upgradeable -> IERC20Upgradeable).

**Comment by rya-sge** [comment]
Thank you for your answer. 
I think it is always better to be sure that all is fine, but it is Ok, it is not necessary to make integration tests with the CMTAT.
