### ISSUE TITLE
Unit test on POT

### ISSUE THREAD

**Issue by rya-sge** [CMTA/DVP#16]
Unless I am mistaken, Unit tests on the contract [POT.sol](https://github.com/CMTA/DVP/blob/main/src/solidity/contracts/POT/POT.sol) are missing

I think it is important to check individual functions to be sure that each function works as intended.

**Comment by mh-targens** [comment]
There exists an extensive test for POT.sol. However, we do not intend to ship it as part of the DvP. The POT contract itself is supposed to be included via npm in the future.

**Comment by rya-sge** [comment]
Ok perfect, thank you for your answer
