### ISSUE TITLE
DvP test missing + doc

### ISSUE THREAD

**Issue by rya-sge** [CMTA/DVP#17]
The function **unpause** seem not be tested in testDVP_pause.ts.

The tests made in TestDVP_upgrade.ts & TestDVP_common are not in the documentation (Unittests_DvP_SC.xlsx)

**Comment by mh-targens** [comment]
The unpause function is tested in the extended test in the branch Test_unpause. PR: https://github.com/CMTA/DVP/pull/19
Unittests_DvP_SC.xlsx will be extended to include TestDVP_upgrade.ts when https://github.com/CMTA/DVP/pull/18 was merged to avoid merge conficts.
TestDVP_common.ts is only a base class without tests of its own.

**Comment by mh-targens** [comment]
TestDVP_upgrade.ts is now listed in Unittests_DvP_SC.xlsx.
